splash page and testing coverage completed, small edits made to other…
Xaeonmy-Team/bs-frontend pull request #3
Opened 2024-03-07 22:32 UTC by jayfr1122

… pages to guide rendering appropriately

2024-03-07 22:36 UTC, elysemontano requested changes
I am seeing files called HeaderNon and FooterNon that looks the same as Header and Footer. I also don't see testing for Header and Footer

2024-03-07 22:38 UTC, jayfr1122 commented
head non and footer non are non functioning header and footer. just purely for aesthetics, but needed to be made as components for other future pages sorry for the confusion those will be better serviced when we get to the header and footer functionality

2024-03-07 22:40 UTC, jayfr1122 commented
im making more changes will ping for an update on slack

2024-03-08 00:28 UTC, elysemontano approved these changes

2024-03-08 00:47 UTC, merged